on:
  pull_request:
    branches:
      - release-candidate
    types: [closed]

jobs:
  bump-version:
    if: github.event.pull_request.merged == true # run only when a branch is merged on "release-candidate"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: release-candidate # checkout on "release-candidate" branch
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: setup git config
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub action"
    - name: bump minor version on "package.json"
      run: npm version minor
    - name: push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
  # update-changelog:
