on:
  pull_request:
    branches:
      - bugfix
      - release-candidate
    types: [ closed ]

jobs:
  update-changelog:
    # https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359
    if: github.event.pull_request.merged == true # run only when a PR has been merged (someone pushed the green button).
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }} # checkout on PR target branch ("bugfix" or "release-candidate")

    - name: setup git config
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub action"

    - name: update CHANGELOG.md file
      run: chmod +x .github/scripts/update-changelog.sh && ./.github/scripts/update-changelog.sh

    - name: push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
